name: de_weather
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  fluttertoast: ^8.2.6
  get_it: ^7.7.0
  injectable: ^2.4.2
  intl: ^0.19.0
  dio: ^5.4.3+1
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sentry_flutter: ^8.3.0
  auto_route: ^8.2.0
  animated_splash_screen: ^1.3.0
  freezed_annotation: ^2.4.1
  flow_builder: ^0.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_gen_runner: ^5.6.0
  build_runner: ^2.4.11
  injectable_generator: ^2.6.1
  auto_route_generator: ^8.0.0
  hive_generator: ^2.0.1
  freezed: ^2.5.2

flutter:
  uses-material-design: true
